version: "3"

services:
  web:
    build: .
    volumes:
      - ./:/go/src/app/
      - ./go.mod:/go/src/app/go.mod
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
